// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSystem.Infrastructure.Data;

#nullable disable

namespace VotingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(VotingDbContext))]
    [Migration("20260304123426_AddSimulationEntities")]
    partial class AddSimulationEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("VotingSystem.Domain.Entities.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Candidates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("VotingSystem.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCandidate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VotingSystem.Domain.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("VotingSystem.Domain.Simulation.Entities.CandidateManifesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EconomyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EducationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WelfarePoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CandidateManifestos");
                });

            modelBuilder.Entity("VotingSystem.Domain.Simulation.Entities.TrendEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EconomyMultiplier")
                        .HasColumnType("REAL");

                    b.Property<double>("EducationMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SecurityMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WelfareMultiplier")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TrendEvents");
                });

            modelBuilder.Entity("VotingSystem.Domain.Simulation.Entities.VoterPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EconomyWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("EducationWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SecurityWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("WelfareWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("VoterPersonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "「経済」重視。高齢者向け福祉や増税を嫌う。",
                            EconomyWeight = 1.5,
                            EducationWeight = 0.5,
                            Name = "ソウタ（20代・低所得フリーター）",
                            SecurityWeight = 0.20000000000000001,
                            WelfareWeight = -1.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "「子育て」最重視。現役世代への負担増を嫌う。",
                            EconomyWeight = 0.80000000000000004,
                            EducationWeight = 2.0,
                            Name = "ミキ（30代・中間層会社員）",
                            SecurityWeight = 0.5,
                            WelfareWeight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = "「経済」重視。ばらまき福祉を極端に嫌う。",
                            EconomyWeight = 2.0,
                            EducationWeight = 0.5,
                            Name = "ケンジ（40代・富裕層IT経営者）",
                            SecurityWeight = 0.5,
                            WelfareWeight = -1.5
                        },
                        new
                        {
                            Id = 4,
                            Description = "「福祉」「治安」重視。変化や年金カットを極端に嫌う。",
                            EconomyWeight = -0.5,
                            EducationWeight = -0.5,
                            Name = "トメ（70代・年金生活者）",
                            SecurityWeight = 1.5,
                            WelfareWeight = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "「治安（防災）」「経済（地方創生）」重視。都市部偏重を嫌う。",
                            EconomyWeight = 1.0,
                            EducationWeight = 0.20000000000000001,
                            Name = "マコト（50代・地方農家）",
                            SecurityWeight = 1.5,
                            WelfareWeight = 0.80000000000000004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
